[tool.poetry]
name = "klerk"
version = "0.1.0"
description = ""
authors = ["Reijhanniel Jearl Campos <devcsrj@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
