klerk:
  senate:
    uri: http://senate.gov.ph/
    congress:
      17:
        - 3R
  house:
    uri: http://congress.gov.ph/
    congress:
      17:
        - 3R
  output-dir: build/journals/
  parsr-uri: "http://localhost:3001"

spring:
  datasource:
    url: "jdbc:h2:./build/klerk.db"
  batch:
    job:
      enabled: true
#      names: collateJournals,extractJournals
      names: extractJournals
#      names: collateJournals